### ISSUE TITLE
GitHub Apps support?

### ISSUE THREAD

**Issue by nnordrum** [knative-sandbox/eventing-github#104]
Is there a reason the GitHub Apps API isn’t used/supported? It’s been out for a while and is pretty widely supported. Would be nice to use the Apps rate limiting instead of the legacy rate limiting.

I don’t even see an issue in the backlog...

**Comment by lionelvillard** [comment]
@nnordrum I think that's be a great addition. 

Besides https://docs.github.com/en/rest/reference/apps#get-a-webhook-configuration-for-an-app, what else would you like to see?

**Comment by nnordrum** [comment]
I’m far from an expert on this module, but you could use a “shared hook” that would receive all the events, so you wouldn’t have to connect back to GitHub to create/reconcile hooks. _Assuming_ creating the hook is the only reason you need (write) access to GitHub, with an App you could bypass this entirely and just receive events. You’d need permissions of some kind if you want to set the hooks URL/secret, but I think that would be something you could set manually. If all you have to do is receive the events and never connect back to GitHub, it should be easy to implement.

**Comment by nnordrum** [comment]
If all we’re doing with the credentials is getting/setting the location of the shared hook, I’d think there’s a better way as that’s a lot of dependencies for minimal benefit. If we’re connecting back for other stuff, then fine.

**Comment by antoineco** [comment]
@nnordrum what would the flow look like with a GitHub app? An owner of the `knative-sandbox` organization would have to register a "Knative event source" app which users would have to add manually to their repo I suppose?

**Comment by nnordrum** [comment]
So GitHub Apps have a single WebHook regardless of how many org/repos (I’m just going to use org in the future, but you can install in just a repo) are using the App. To get events from a new org, you “install” an app in an org. After you do this, GitHub sends the events to the hook that the App has already configured. To contrast to the PAT way, there’s no hook to “install”: it’s already configured when you setup the app. To stop getting events, you just “uninstall” the app from an org.

Think of it like CircleCI (just randomly picked them). They have one ingress webhook that gets _all_ the events from GitHub. They don’t have to change their end/config at all to accept a new customer. New customers start using the hook and send them only the events they need/request. They don’t have to have to put in some hook and configure it correctly, GitHub does all of that. 

If we’re just receiving the events because GitHub is managing the orgs instead of us, I don’t think we need any credentials in the hook. At most we just, optionally, need the shared secret to verify the message. Otherwise, it’s exactly the same as before (just more possible event types). It’s actually easier because there’s less you have to do...

**Comment by antoineco** [comment]
Sounds interesting indeed.

We'll have to provide very good documentation if we implement this, because the setup is more complex that it is today. The user must first create a source in Knative, then wait for it to report a URL, and finally go create an app in GitHub (which is quite a few steps on its own) pointing at that URL.

My gut feeling is that we shouldn't drop the "old" mode completely, because having a source that automatically performs its own setup is a great experience for newcomers.

**Comment by nnordrum** [comment]
I agree we shouldn’t drop the “old” version; just have an app mode and a PAT mode. They’re substantially similar...

I think the setup is _slightly_ more complicated, but there are fewer moving parts (I’m going to assume the Secret to connect back is not needed, which I’m pretty sure is a valid assumption), just more dependent activities.

Thinking about it, it would be this:
1. Create GitHubAppSource which has the secret the hook will use. 
2. Determine where hook is
3. Create GitHubApp with the hook url from step 2, and the secret from step 1

I think that’s it actually... you’d obviously have to install the app to get events, but that’s not a KNative activity...

**Comment by nnordrum** [comment]
I basically just said what you said... I shouldn’t read a comment, wait 4hrs, then reply...

**Comment by nnordrum** [comment]
Do you/anybody have a dummies guide to adding a Source to this? operator-sdk is giving me errors and kubebuilder says I need to init. I just don’t want to miss something or do a bunch of extra work since this would be my first operator...

**Comment by lionelvillard** [comment]
It seems there is an API to create an app, so it should be possible to reproduce the same GitHubSource UX, just different parameters.

We don't rely on operator-sdk and/or kubebuilder. A good starting point is to look at the doc: https://knative.dev/docs/eventing/samples/writing-event-source/. 

Also feel free to reach out on Slack (#eventing-sources channel) for questions. We all be very happy to help :-)
