### ISSUE TITLE
Add the eventing source label to indicate the source type

### ISSUE THREAD

**Issue by houshengbo** [knative-sandbox/eventing-github#149]
**Describe the bug**
All eventing sources should have a label to indicate the source type for all the released resources.
The similar label is `networking.knative.dev/ingress-provider` for all the serving ingresses.
I propose to add the label `contrib.eventing.knative.dev/source-provider` for all the available resources.
Since this repository is for eventing-github, we will use `contrib.eventing.knative.dev/source-provider: github`.

 **Expected behavior**
Add the label `contrib.eventing.knative.dev/source-provider: github` for all resources.

 **Knative release version**
main

 **Additional context**
Facilitate the support in knative operator

**Comment by lionelvillard** [comment]
I think the label should be `sources.knative.dev/source-provider`.

/cc @n3wscott

**Comment by n3wscott** [comment]
If you look at https://github.com/knative-sandbox/eventing-github/blob/main/config/core/300-githubsource.yaml#L26

this makes EventType resources which have the information you are interested in. See pingsource:

```
(╯°□°)╯︵  kubectl get eventtype
NAME                               TYPE                       SOURCE                                                SCHEMA   BROKER    DESCRIPTION   READY   REASON
7bf545ee6f5695e12838becea572c02a   dev.knative.sources.ping   /apis/v1/namespaces/default/pingsources/ping-source            default                 True
```

There is no link back to the term "provider" in our specs or cloudevents so I am not sure what you are thinking this might be. GitHub is the producer of events, but the GitHubSource instance is provided by Knative, as seen in the api group of the resource.

So I am confused.

**Comment by houshengbo** [comment]
It looks like I used an incorrect term for the eventing source.
The `***-provider` is what I copied from the `ingress-provider`.
Would it be better if we use `sources.knative.dev/source-provider: github` to label all the resources released by eventing-github?

**Comment by houshengbo** [comment]
Thanks to @n3wscott 
Let's be compliant with the cloud events. The eventing source `github` is the `service` based on the terminology.
Can `sources.knative.dev/service: github` be the candidate?

**Comment by lionelvillard** [comment]
@houshengbo do you still need this? If yes can you reopen this issue?
