### ISSUE TITLE
Update CRD apiVersion to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/eventing-github#223]
As CRD still uses [`apiextensions.k8s.io/v1beta1`](https://github.com/knative-sandbox/eventing-github/blob/release-1.0/config/core/300-githubsource.yaml#L15
) it fails to deploy eventing-github on k8s 1.22.

```shell
$ kubectl apply -f config/core/300-githubbinding.yaml
error: unable to recognize "config/core/300-githubbinding.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

It was remove since k8s 1.22 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

**Comment by matzew** [comment]
same for the `admissionregistration.k8s.io/v1beta1` - deprecated in v1.16+, unavailable in v1.22+

https://github.com/knative-sandbox/eventing-github/blob/main/config/core/500-webhook-configuration.yaml#L15

**Comment by lionelvillard** [comment]
@zhlhahaha @hamees-sayed let's know if the fix works for you
