### ISSUE TITLE
Vanity GitHub Webhook URL

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-github#65]
Copied from https://github.com/knative/eventing-contrib/issues/1171

**Problem**
The MT githubsource controller generates webhook of the form `http://githubsource-adapter.knative-sources.<domain>/<ns>/<name>`

where `ns` and `name` corresponds the githubsource CR.

Instead it should generate webhook of the form `http://<name>.<ns>.<domain>`. 

**Context**
See https://github.com/knative/eventing-contrib/issues/1131#issuecomment-612559118 for more details. 

Depends on https://docs.google.com/document/d/1xK-g55kFdRRpYsiHyesmYWKURWi1sJlIWxMwkRmlyuM/edit#

`DomainMapping` will land in Knative Serving 0.19. Documentation is here: https://github.com/knative/docs/pull/3017/files

**Comment by abrennan89** [comment]
/remove-lifecycle stale

@lionelvillard is this still relevant and does it require a docs issue?

**Comment by lionelvillard** [comment]
this is still relevant.
