### ISSUE TITLE
github event source doesn't pass along original headers

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-github#86]
From https://github.com/knative/eventing-contrib/issues/537

I would expect the original github event headers to still be in the message passed to the sink - as appropriate. In my testing I'm not seeing the Github-Delivery and Github-Event headers. They do appear as Ce-Github-... though. However, if I have existing code that expects a github event then I shouldn't have to change my code to look for Ce-Github... headers. The conversion to a CloudEvent should augment the event, not remove the github-ness of it w.r.t. headers.

**Comment by runzexia** [comment]
I have encountered the same problem. Many scm libraries now parse the default headers provided by webhook. E.g. https://github.com/jenkins-x/go-scm/blob/master/scm/driver/github/webhook.go#L46
Is pass along original headers acceptable in cloudevent?
If it is an acceptable solution, I can implement it

**Comment by runzexia** [comment]
After doing some research, I found that currently `cloudevent sdk` cannot send requests with custom headers.
In eventing (for example broker), `cloudevent sdk` is not used to send requests.

**Comment by lionelvillard** [comment]
@n3wscott @slinkydeveloper
